version: '3.6'
services:   
  influxdb:
    container_name: influxdb
    image: "influxdb:1.8"
    restart: unless-stopped
    user: "${LOCAL_USER}:${LOCAL_USER}"
    ports:
    - "8086:8086"
    environment:
    - INFLUXDB_HTTP_FLUX_ENABLED=false
    - INFLUXDB_REPORTING_DISABLED=false
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUX_USERNAME="admin"
    - INFLUX_PASSWORD="admin"
    - INFLUXDB_UDP_ENABLED=false
    - INFLUXDB_UDP_BIND_ADDRESS=0.0.0.0:8086
    - INFLUXDB_UDP_DATABASE=udp
    volumes:
    - ./influxdb:/var/lib/influxdb

  chronograf:
    container_name: chronograf
    image: chronograf:latest
    restart: unless-stopped
    user: "${LOCAL_USER}:${LOCAL_USER}"
    environment:
  #see https://docs.influxdata.com/chronograf/v1.9/administration/config-options/
    - INFLUXDB_URL="http://192.168.0.127:8086"
    - INFLUXDB_USERNAME="admin"
    - INFLUXDB_PASSWORD="admin"
    ports:
    - "8889:8888"
    volumes:
    - ./chronograf:/var/lib/chronograf
    depends_on:
    - influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: unless-stopped
    user: ${LOCAL_USER}:${LOCAL_USER}
    ports:
    - "3000:3000"
    volumes:
    - ./grafana/data:/var/lib/grafana
    - ./grafana/log:/var/log/grafana